version: "3"

services:
    web:
        image: stephenroille/react
        build:
            context: .
            dockerfile: dev.Dockerfile
        ports:
            - 80:3000
        volumes:
            - .:/usr/app
    test:
        build:
            context: .
            dockerfile: dev.Dockerfile
        command: ["test"]
        volumes:
            - .:/usr/app
